
environment:
  matrix:

   - job_name: Windows
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
     configuration: Debug
     platform: x64

   - job_name: Windows
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
     configuration: Release
     platform: x64

   - job_name: Windows
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
     configuration: Retail
     platform: x64

   - job_name: Linux
     APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
     buildcfg: debug64

   - job_name: Linux
     APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
     buildcfg: release64

   - job_name: Linux
     APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
     buildcfg: retail64

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
     buildcfg: debug64

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
     buildcfg: release64

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
     buildcfg: retail64

shallow_clone: true

install:
- git submodule init
- git submodule update

for:

# ======================================
# Windows
# ======================================

  -
    matrix:
      only:
      - job_name: Windows
      - QTDIR: C:\Qt\6.9.3\msvc2022_64

    init:
    - set QTDIR=C:\Qt\6.9.3\msvc2022_64
    - git clone --depth 1 https://github.com/rjpcomputing/luaforwindows luaforwindows
    - copy %cd%\luaforwindows\files\lua5.1.exe %cd%\luaforwindows\files\lua.exe
    - set PATH=%cd%\luaforwindows\files;C:\Qt\6.9.3\msvc2022_64\bin;%PATH%
    - git clone --depth 1 https://github.com/RudjiGames/MTuner   MTuner
    - cd MTuner && git submodule update --init --recursive

    install:
      - zidar\tools\bin\windows\genie.exe --file=src\MTuner\scripts\genie.lua vs2022

    build:
      project: MTuner\.zidar\windows\vs2022\MTuner\projects\vs2022\MTuner.sln

# ======================================
# Linux
# ======================================

  -
    matrix:
      only:
      - job_name: Linux

    init:
      - sudo apt install -y lua5.3 lua-filesystem
      - sudo ln -sf /usr/bin/lua5.3 /usr/bin/lua
      - export QTDIR="$HOME/Qt/6.9.2"
      - export PATH="$HOME/Qt/6.9.2/bin:$HOME/Qt/6.9.2/libexec:$PATH"
      - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$HOME/Qt/6.9.2/lib/pkgconfig"
      - export LD_LIBRARY_PATH="$HOME/Qt/6.9.2/lib:$HOME/Qt/6.9.2:$LD_LIBRARY_PATH"
      - git clone --depth 1 https://github.com/bkaradzic/GENie     GENie		# build GENie from source: `GLIBC_2.29' not found
      - git clone --depth 1 https://github.com/RudjiGames/MTuner   MTuner
      - cd GENie && make && cd ..
      - cd MTuner && git submodule update --init --recursive

    install:
      - ./GENie/bin/linux/genie --file=src/MTuner/scripts/genie.lua --gcc=linux-gcc gmake

    build_script:
      - cd ./.zidar/linux/linux-gcc/MTuner/projects/
      - make config=${buildcfg}

# ======================================
# OSX
# ======================================

  -
    matrix:
      only:
      - job_name: OSX

    init:
      - export QTDIR="$HOME/Qt/6.6.1/macos/"
      - export PATH="$HOME/Qt/6.6.1/macos/bin:$HOME/Qt/6.6.1/macos/libexec:$PATH"
      - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$HOME/Qt/6.6.1/macos/lib/pkgconfig"
      - curl -L -R -O https://www.lua.org/ftp/lua-5.4.7.tar.gz
      - tar zxf lua-5.4.7.tar.gz
      - cd lua-5.4.7 && sudo make all test && sudo make install && cd ..
      - git clone --depth 1 https://github.com/bkaradzic/GENie GENie  # build GENie from source: we don't know the target CPU, can't use ARM binary from 'zi'
      - cd GENie && make && cd ..
      - git clone --depth 1 https://github.com/RudjiGames/MTuner   MTuner
      - cd MTuner && git submodule update --init --recursive

    install:
      - ./GENie/bin/darwin/genie --file=src/MTuner/scripts/genie.lua --gcc=osx-x64 gmake

    build_script:
      - cd ./.zidar/osx/clang/MTuner/projects/
      - make config=${buildcfg}
